name: Android rom application

on:
  workflow_dispatch:
    inputs:
      romUrl:
        description: 'ROM Url'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        path: tools
        repository: wuxianlin/android_rom_tools

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install axel brotli maven
        ./tools/setup.sh ${{ secrets.GITHUB_TOKEN }}
        python -m pip install --upgrade pip
        if [ -f tools/requirements.txt ]; then pip install -r tools/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run
      run: |
        bash jadx.sh
      env:
        ROM_URL: ${{ inputs.romUrl }}

    - name: archive
      run: |
        tar -czf rom-decompiled-jadx.tar.gz rom-decompiled-jadx

    - uses: actions/upload-artifact@v4
      with:
        name: rom-decompiled-jadx
        path: rom-decompiled-jadx.tar.gz
